sudo: required

services:
    - docker

before_install:
    - sudo chmod 777 src/wait-for-it.sh
    - bash build.sh

script:
    - docker exec -it dev-test-application vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)