sudo: required

language: php

services:
    - docker

before_install:
    - sudo chmod 777 src/wait-for-it.sh
    - docker-compose up -d

script:
    - docker exec -it dev-test-application vendor/bin/phpunit
